find_path(PORTAUDIO_INCLUDE_DIRS NAMES portaudio.h PATHS /usr/include)
find_library(PORTAUDIO_LIBRARY NAMES portaudio)
find_library(PORTAUDIOCPP_LIBRARY NAMES portaudiocpp)

set(PORTAUDIO_LIBRARIES ${PORTAUDIO_LIBRARY} ${PORTAUDIOCPP_LIBRARY})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PortAudio DEFAULT_MSG PORTAUDIO_LIBRARIES PORTAUDIO_INCLUDE_DIRS)
